Cleaned Ubuntu 12.04 Bootstrap Image

diff --git a/bootstrap/ubuntu-12.04/usr/local/bin/generate-locales b/bootstrap/ubuntu-12.04/usr/local/bin/generate-locales
--- a/bootstrap/ubuntu-12.04/usr/local/bin/generate-locales
+++ b/bootstrap/ubuntu-12.04/usr/local/bin/generate-locales
@@ -2,8 +2,8 @@
 
 set -o pipefail  # trace ERR through pipes
 set -o errtrace  # trace ERR through 'time command' and other functions
-set -o nounset   ## set -u : exit the script if you try to use an uninitialised variable
-set -o errexit   ## set -e : exit the script if any statement returns a non-true return value
+set -o nounset   # set -u : exit the script if you try to use an uninitialised variable
+set -o errexit   # set -e : exit the script if any statement returns a non-true return value
 
 if [[ "$(lsb_release -r -s | cut -f 1 -d .)" -ge "16" ]]; then
     # Ubuntu 16.04 or later
