Amended dev. image phalconphp/php:7.1-dev

diff --git a/php/7.1-dev/usr/local/bin/docker-php-entrypoint b/php/7.1-dev/usr/local/bin/docker-php-entrypoint
--- a/php/7.1-dev/usr/local/bin/docker-php-entrypoint
+++ b/php/7.1-dev/usr/local/bin/docker-php-entrypoint
@@ -1,5 +1,6 @@
-#!/bin/sh
-set -e
+#!/bin/bash
+
+set -o errexit   # set -e : exit the script if any statement returns a non-true return value
 
 # first arg is `-f` or `--some-option`
 if [ "${1#-}" != "$1" ]; then
diff --git a/php/7.1-dev/usr/local/bin/docker-php-ext-configure b/php/7.1-dev/usr/local/bin/docker-php-ext-configure
--- a/php/7.1-dev/usr/local/bin/docker-php-ext-configure
+++ b/php/7.1-dev/usr/local/bin/docker-php-ext-configure
@@ -1,5 +1,6 @@
-#!/bin/sh
-set -e
+#!/bin/bash
+
+set -o errexit   # set -e : exit the script if any statement returns a non-true return value
 
 # prefer user supplied CFLAGS, but default to our PHP_CFLAGS
 : ${CFLAGS:=$PHP_CFLAGS}
@@ -8,15 +9,16 @@ set -e
 export CFLAGS CPPFLAGS LDFLAGS
 
 srcExists=
-if [ -d /usr/src/php ]; then
+if [ -d ${PHP_SOURCE_DIR} ]; then
 	srcExists=1
 fi
+
 docker-php-source extract
 if [ -z "$srcExists" ]; then
-	touch /usr/src/php/.docker-delete-me
+	touch ${PHP_SOURCE_DIR}/.docker-delete-me
 fi
 
-cd /usr/src/php/ext
+cd ${PHP_SOURCE_DIR}/ext
 
 ext="$1"
 if [ -z "$ext" ] || [ ! -d "$ext" ]; then
@@ -24,7 +26,7 @@ if [ -z "$ext" ] || [ ! -d "$ext" ]; then
 	echo >&2 "   ie: $0 gd --with-jpeg-dir=/usr/local/something"
 	echo >&2
 	echo >&2 'Possible values for ext-name:'
-	find /usr/src/php/ext \
+	find ${PHP_SOURCE_DIR}/ext \
 			-mindepth 2 \
 			-maxdepth 2 \
 			-type f \
@@ -36,21 +38,6 @@ if [ -z "$ext" ] || [ ! -d "$ext" ]; then
 	exit 1
 fi
 shift
-
-pm='unknown'
-if [ -e /lib/apk/db/installed ]; then
-	pm='apk'
-fi
-
-if [ "$pm" = 'apk' ]; then
-	if \
-		[ -n "$PHPIZE_DEPS" ] \
-		&& ! apk info --installed .phpize-deps > /dev/null \
-		&& ! apk info --installed .phpize-deps-configure > /dev/null \
-	; then
-		apk add --no-cache --virtual .phpize-deps-configure $PHPIZE_DEPS
-	fi
-fi
 
 set -x
 cd "$ext"
diff --git a/php/7.1-dev/usr/local/bin/docker-php-ext-enable b/php/7.1-dev/usr/local/bin/docker-php-ext-enable
--- a/php/7.1-dev/usr/local/bin/docker-php-ext-enable
+++ b/php/7.1-dev/usr/local/bin/docker-php-ext-enable
@@ -1,5 +1,6 @@
-#!/bin/sh
-set -e
+#!/bin/bash
+
+set -o errexit   # set -e : exit the script if any statement returns a non-true return value
 
 cd "$(php -r 'echo ini_get("extension_dir");')"
 
@@ -76,7 +77,7 @@ for module in $modules; do
 		continue
 	fi
 
-	ini="/usr/local/etc/php/conf.d/${iniName:-"docker-php-ext-$ext.ini"}"
+	ini="${PHP_INI_DIR}/conf.d/${iniName:-"docker-php-ext-$ext.ini"}"
 	if ! grep -q "$line" "$ini" 2>/dev/null; then
 		echo "$line" >> "$ini"
 	fi
diff --git a/php/7.1-dev/usr/local/bin/docker-php-ext-install b/php/7.1-dev/usr/local/bin/docker-php-ext-install
--- a/php/7.1-dev/usr/local/bin/docker-php-ext-install
+++ b/php/7.1-dev/usr/local/bin/docker-php-ext-install
@@ -1,5 +1,6 @@
-#!/bin/sh
-set -e
+#!/bin/bash
+
+set -o errexit   # set -e : exit the script if any statement returns a non-true return value
 
 # prefer user supplied CFLAGS, but default to our PHP_CFLAGS
 : ${CFLAGS:=$PHP_CFLAGS}
@@ -8,15 +9,15 @@ set -e
 export CFLAGS CPPFLAGS LDFLAGS
 
 srcExists=
-if [ -d /usr/src/php ]; then
+if [ -d ${PHP_SOURCE_DIR} ]; then
 	srcExists=1
 fi
 docker-php-source extract
 if [ -z "$srcExists" ]; then
-	touch /usr/src/php/.docker-delete-me
+	touch ${PHP_SOURCE_DIR}/.docker-delete-me
 fi
 
-cd /usr/src/php/ext
+cd ${PHP_SOURCE_DIR}/ext
 
 usage() {
 	echo "usage: $0 [-jN] ext-name [ext-name ...]"
@@ -78,23 +79,6 @@ if [ -z "$exts" ]; then
 	exit 1
 fi
 
-pm='unknown'
-if [ -e /lib/apk/db/installed ]; then
-	pm='apk'
-fi
-
-apkDel=
-if [ "$pm" = 'apk' ]; then
-	if [ -n "$PHPIZE_DEPS" ]; then
-		if apk info --installed .phpize-deps-configure > /dev/null; then
-			apkDel='.phpize-deps-configure'
-		elif ! apk info --installed .phpize-deps > /dev/null; then
-			apk add --no-cache --virtual .phpize-deps $PHPIZE_DEPS
-			apkDel='.phpize-deps'
-		fi
-	fi
-fi
-
 popDir="$PWD"
 for ext in $exts; do
 	cd "$ext"
@@ -110,10 +94,6 @@ for ext in $exts; do
 	cd "$popDir"
 done
 
-if [ "$pm" = 'apk' ] && [ -n "$apkDel" ]; then
-	apk del $apkDel
-fi
-
-if [ -e /usr/src/php/.docker-delete-me ]; then
+if [ -e ${PHP_SOURCE_DIR}/.docker-delete-me ]; then
 	docker-php-source delete
 fi
diff --git a/php/7.1-dev/usr/local/bin/docker-php-source b/php/7.1-dev/usr/local/bin/docker-php-source
--- a/php/7.1-dev/usr/local/bin/docker-php-source
+++ b/php/7.1-dev/usr/local/bin/docker-php-source
@@ -1,7 +1,6 @@
-#!/bin/sh
-set -e
+#!/bin/bash
 
-dir=/usr/src/php
+set -o errexit   # set -e : exit the script if any statement returns a non-true return value
 
 usage() {
 	echo "usage: $0 COMMAND"
@@ -9,22 +8,22 @@ usage() {
 	echo "Manage php source tarball lifecycle."
 	echo
 	echo "Commands:"
-	echo "   extract  extract php source tarball into directory $dir if not already done."
-	echo "   delete   delete extracted php source located into $dir if not already done."
+	echo "   extract  extract php source tarball into directory ${PHP_SOURCE_DIR} if not already done."
+	echo "   delete   delete extracted php source located into ${PHP_SOURCE_DIR} if not already done."
 	echo
 }
 
 case "$1" in
 	extract)
-		mkdir -p "$dir"
-		if [ ! -f "$dir/.docker-extracted" ]; then
-			tar -Jxf /usr/src/php.tar.xz -C "$dir" --strip-components=1
-			touch "$dir/.docker-extracted"
+		mkdir -p "${PHP_SOURCE_DIR}"
+		if [ ! -f "${PHP_SOURCE_DIR}/.docker-extracted" ]; then
+			tar -Jxf /usr/src/php.tar.xz -C "${PHP_SOURCE_DIR}" --strip-components=1
+			touch "${PHP_SOURCE_DIR}/.docker-extracted"
 		fi
 		;;
 
 	delete)
-		rm -rf "$dir"
+		rm -rf "${PHP_SOURCE_DIR}"
 		;;
 
 	*)
