Minor fixes for php/7.1-dev

diff --git a/php/7.1-dev/usr/local/bin/docker-php-entrypoint b/php/7.1-dev/usr/local/bin/docker-php-entrypoint
--- a/php/7.1-dev/usr/local/bin/docker-php-entrypoint
+++ b/php/7.1-dev/usr/local/bin/docker-php-entrypoint
@@ -1,9 +1,9 @@
 #!/bin/bash
 
-set -o errexit   # set -e : exit the script if any statement returns a non-true return value
+set -o errexit # set -e : exit the script if any statement returns a non-true return value
 
 # Enable core dumps
-ulimit -c unlimited || true
+ulimit -c unlimited
 echo "Set: ulimit -c unlimited"
 
 # Specify filename and path for core dumps
